name: Create Assets

# run: 
# git tag -a v0.2.4 -m "Test Release 0.2.4"
# git push origin v0.2.4

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Create assets
    runs-on: windows-latest
    strategy:
      matrix:
        distribution: [ 'win-x64', 'linux-x64'] # , 'osx-x64' , 'win-arm64', 'win-x86',  'linux-arm64', 'osx-arm64' ]
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Get the tag without the 'v' prefix
        id: format_tag
        run: echo "::set-output name=tag::${GITHUB_REF:11}"

      - name: install nuget repo
        run: |
          dotnet nuget add source --username m-v-k --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Azlon-io/index.json"

      - name: DotNet Publish
        run: |
          echo ${{ steps.format_tag.outputs.tag }}
          cd src/Azlon.Dataport.Console
          dotnet publish -c Release -o ./artifacts \
            --runtime ${{ matrix.distribution }} \
            --self-contained true \
            -p:PublishTrimmed=true \
            -p:TrimMode=Link \
            -p:PublishSingleFile=true \
            -p:AssemblyNameVersion=azlonctl \
            -p:AssemblyVersion=${{ steps.format_tag.outputs.tag }} \
            -p:Version=${{ steps.format_tag.outputs.tag }}
      
      - name: Zip
        run: |
          mkdir ./src/Azlon.Dataport.Console/zip
          cd ./src/Azlon.Dataport.Console/artifacts
          zip -r ../zip/azlonctl-${{ matrix.distribution }}.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-publish-${{ matrix.distribution }}
          path: ./src/Azlon.Dataport.Console/zip/
  
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.AZLON_DATAPORT_CLI_PAT }}
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  assets:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'win-x64', 'linux-x64'] # , 'osx-x64' , 'win-arm64', 'win-x86',  'linux-arm64', 'osx-arm64' ] # add only if requested by a consumer
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dotnet-publish-${{ matrix.distribution }}
        path: ./artifacts/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./artifacts/azlonctl-${{ matrix.distribution }}.zip
        asset_name: azlonctl-${{ matrix.distribution }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.AZLON_DATAPORT_CLI_PAT }}
