name: Test Create Assets

on:
  push:
    branches:
      - 'devops/test-pipeline'

jobs:
  publish:
    name: Create assets
    runs-on: windows-latest
    strategy:
      matrix:
        distribution: [ 'win-x64'] # , 'osx-x64' , 'win-arm64', 'win-x86',  'linux-arm64', 'osx-arm64' ]
    steps:

      - name: Get the tag without the 'v' prefix
        id: format_tag
        shell: bash
        run: |
          TAG=${{ github.ref }}
          echo $TAG
          TAG=${TAG:11}
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "test"

      - name: DotNet Publish
        shell: bash
        run: |
          echo ${{ steps.format_tag.outputs.tag }}
